### PR TITLE
Add support for masks and screenshots of individual elements

### PR DESCRIPTION
**Pull request by DiogoGarrido**
Additional changes:
- Changes options per screenshot
- Remove the need for the PID file
- Improved README
- Improved Documentation
- Improved Example Project

### CODE REVIEW

**Comment by skwakman** [comment]
@fvanwijk?

**Comment by skwakman** [comment]
@DiogoGarrido Nice additions! However, since the merge of #22 there are some merge conflicts to take care of. Additionally, it seems the example project doesn't work anymore in this PR due to `initRun` not being executed anymore.

**Comment by DiogoGarrido** [comment]
Hi. @skwakman Sorry for the delay. I will make the rebase and fix the initRun. Thanks

**Comment by DiogoGarrido** [comment]
@skwakman  I will close this pull request since I used another branch to make the changes. The new PR is  here https://github.com/xebia/VisualReview-protractor/pull/25. Thanks

**Pull request closed without merging**
