### PR TITLE
added compareSettings for protractor module

### PR DESCRIPTION
**Pull request by FinKingma**
This PR will only add value once PR 71 for Visual Review has been accepted:
https://github.com/xebia/VisualReview/pull/71

In that PR I added the option compareSettings when sending screenshots. This PR will forward provided settings to VisualReview

### CODE REVIEW

**Comment by skwakman** [comment]
Thanks for the PR! Code looks mostly good, however in the README you state that the default precision is 0, but I'm not seeing that in either client or server code. Did I miss that and if so, could you point me to the place where it's guaranteed it has a default value?

**Comment by FinKingma** [comment]
It happens in the PixelComparator.
Clojure just passes the compareSettings through.
In the PixelComparator the precision is set to '0', and if a specified value can be retrieved it will be overwritten.
However, this will break if someone in the future will provide different compareSettings and not precision. I will fix this today.

```
int precision = 0;

      try {
        if (!compareSettings.equals(null) && !compareSettings.equals("null") && !compareSettings.equals("")) {
          JSONObject json = new JSONObject(compareSettings);
          precision = json.getInt("precision");
        }
      }
      catch (Exception e) {
        throw new Exception("compareSettings were incorrectly provided. \n", e);
      }
```

**Comment by skwakman** [comment]
@FinKingma could you fix the conflicts so we can merge this PR?

**Comment by FinKingma** [comment]
Ok conflicts solved!

**Comment by skwakman** [comment]
Sorry for the delay, but it's merged! Thanks!

**Pull request merged**
